### PR TITLE
Done

### PR DESCRIPTION
**Pull request by tripscripts**

### CODE REVIEW

**Comment by aturkewi** [comment]
@tripscripts I merged this in, but you'll notice that the image links you provided lead to stock Image is Missing photos. You may want to do another PR to update those.

**Comment by tripscripts** [comment]
forgot about this; I'd rather you removed me 

@aturkewi thanks

**Comment by aturkewi** [comment]
Hey @tripscripts 
If you'd like to be removed, can you please put in a PR for this? Just go through and remove the changes you made in this one :)

Please feel free to let me know if you have any questions!

**Comment by tripscripts** [comment]
@aturkewi please see https://github.com/tripscripts/learn-deploy-on-day-one-v-000/commit/926bf213ea099dfc577e696f6b31de8eb284baf2

thanks for your help

**Comment by aturkewi** [comment]
Hey @tripscripts I see you made some changes in your repo, but for these changes to get merged into master, you'll have to create a pull request. 

The easiest thing to do is probably to delete your current fork on github, then re-fork this repo (I'm guessing there have been a lot of changes since you originally forked). Then, delete all your info and make another PR to this repo. 

If you have any questions on this, please feel free to reach out!

**Comment by tripscripts** [comment]
@aturkewi hey guy I just submitted pull request #624 

https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/624

thanks for all of your help today!

**Pull request merged**
