### PR TITLE
Done

### PR DESCRIPTION
**Pull request by kade042**

### CODE REVIEW

**Comment by mendelB** [comment]
Hi @kade042 
Everything seems perfect, you're just missing the customized div in the `index.html` file (described in the 'add to the index' part of the lab). 
Please add that and make a new pull request so we can merge your profile. Thanks!

**Comment by kade042** [comment]
Sorry can u add a little bit information about the missing thank you

**Comment by mendelB** [comment]
Sure! So all you need to do is open the `index.html` file, copy one of the `div`s with the class of 'student-card' and paste it on the page using the same formatting, replacing  the info with your own. If you need help with that you can ping me on slack @mendel

**Comment by kade042** [comment]
Oh yeah I did it on my pc but I forgot in nitrous that why thanks

**Pull request merged**
