### PR TITLE
Done

### PR DESCRIPTION
**Pull request by jmaerk235**

### CODE REVIEW

**Comment by adamjonas** [comment]
It appears you've erased the other students from the project. Please add only your profile @jmaerk235 rather than removing others.

**Comment by jmaerk235** [comment]
Would doing a sparse checkout be a good solution to replace all the student-name.html files I deleted?

**Comment by adamjonas** [comment]
Sorry @jmaerk235, not positive I understand what a sparse checkout refers to exactly. The most workflow friendly way to do this would be to `git reset --hard HEAD~1` to go back to the commit you pulled from master and then check out a new branch with `git checkout -b new-branch`. After you make the changes to that branch you can open a new pull request on GitHub which will allow you to manually select this repository as an option to issue the PR to. 

OR

To blow away your local version. Re-clone, make the changes and re-open the PR, which is much more straight forward.

Up to you.

**Comment by jmaerk235** [comment]
I tried the first option you told me and I'm not sure that I did it correct. I was able to get the code and fix it but when trying to push it back to github I pushed only the new branch I made adding-profile.

**Comment by jmaerk235** [comment]
I am just going to redo it so I manually deleted my repository.

**Comment by jmaerk235** [comment]
I have tried many ways to fix this and I have the correct version at
https://github.com/jmaerk235/learn-deploy-on-day-one-v-000 but I am unable
to push my new changes to github.

// ♥ git push origin master

Everything up-to-date

[13:40:55] (master) learn-deploy-on-day-one-v-000

// ♥ git status

On branch master

Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

This is what I get when I attempt to push.

**Comment by adamjonas** [comment]
@jmaerk235 Have you pushed your code you to your fork?

**Comment by jmaerk235** [comment]
Yes my fork jmaerk235/learn-deploy-on-day-one-v-000 is current and ready to
be added to the student repository.

Before I try this I wanted to show you so I don't mess anything up. Will
this work?

[image: Inline image 1]

**Pull request closed without merging**
