### PR TITLE
Done

### PR DESCRIPTION
**Pull request by thesilentc**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi @thesilentc !

Your changes look pretty good, except for one tiny thing.  In `css/styles.css` you changed the "photo placeholder" image.  It's kind of like a "backup image" in case a student's image doesn't load.  Your other changes look ok though!

So if you can change that back, that would be grand.  You can get the old url by looking at the 'file changes' tab of this PR or at [this link](https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/800/files).

Let us know if you need any help!

CC: @aturkewi

**Comment by aturkewi** [comment]
Hey @thesilentc 
One more thing that must change before we can merge this in is that your student card on the `index.html` page should be inside the `.roster-cards-container`. You'll see that there are two comments right above where you edited the `index.html` file noting the end of those containers and all the other student cards are inside those `<div>` tags.
@bhollan ^

**Comment by bhollan** [comment]
This is looking so much better, @thesilentc !
I think we can merge this in with 1 minor change.  There's a background image we load in every `student-card` just in case somebody's image doesn't load.  It looks like you've removed that image and replaced it with your own.  If you could reset that one image, I think this will be all set!

CC: @aturkewi

**Comment by bhollan** [comment]
It looks like you haven't touched this in a while.  I'm going go to close it for now and we can open it again whenever you're ready to work on it.  We can get it merged in then.

CC: @aturkewi

**Pull request closed without merging**
