### PR TITLE
Done

### PR DESCRIPTION
**Pull request by Nicholas-Maxwell**

### CODE REVIEW

**Comment by mendelB** [comment]
Hi @Nicholas-Maxwell
Unfortunately it seems that there are still many file changes that would be harmful to merge...
Did you encounter any issues when forking or cloning this lab?

**Comment by Nicholas-Maxwell** [comment]
Hi Mendel ,

Really?! Wow.. No I didn't have any problems .. I deleted all my original files & forked it all over again

**Comment by Nicholas-Maxwell** [comment]
Contact me on slack

**Comment by aturkewi** [comment]
Hey @Nicholas-Maxwell when you have time, contact me on Slack and I'll give you a hand with this. I'm free until 12pm today and I'm free most of tomorrow.

**Comment by Nicholas-Maxwell** [comment]
Hello Avi, Yea I  have been meaning to take care of this issue. As far as today, I am free after 5. Tomorrow maybe at 12 I will be free and I am free all day on Thursday In which I will be at Flatiron doing work.  So maybe you wanna work in person with me on it.  let me know 

thanks!

**Comment by aturkewi** [comment]
Closing. He made a new PR #396

**Pull request closed without merging**
