### PR TITLE
created student-card

### PR DESCRIPTION
**Pull request by GoodBoyNYC**

### CODE REVIEW

**Comment by aturkewi** [comment]
@GoodBoyNYC it looks like you deleted this file: assets/img/student-name-cover.jpg

If you could please add it back with `git co assets/img/student-name-cover.jpg` I can merge this pull request. 

Let me know if you need a hand.

**Comment by GoodBoyNYC** [comment]
I believe I just did so. Let me know if what I did worked.

**Comment by aturkewi** [comment]
@GoodBoyNYC I should have been a bit more clear. You want to add your images with your name in the file name. Your image file names should be something like `llubomir-stanojlovic.jpg` and `llubomir-stanojlovic-cover.jpg`. Also, make sure to make these changes in your css as well. To fix the files you changed, you can run `git co da0d66b assets/img/student-name-cover.jpg`to fix the cover picture and then delete the file named assets/img/student-name.jpg

**Comment by GoodBoyNYC** [comment]
Maybe I'm missing something but my first commit had the images as llubomir-stanojlovic.jpg and llubomir-stanojlovic-cover.jpg and the css had reflected that. I believe I did delete a file explicitly called "student-name-cover.jpg"

**Comment by aturkewi** [comment]
@GoodBoyNYC Your first commit was perfect except for the fact that you deleted a file that wasn't yours `assets/img/student-name-cover.jpg`. That's why the only thing I initially asked was for you to add back the file. This can all get a bit confusing, I know. If you want to chat about it, feel free to catch me on slack (i'm `@avidor`). 
If you can go back to your initial commit and just add that file back in, you should be all set.

**Comment by aturkewi** [comment]
@GoodBoyNYC I'm closing this PR for now because I haven't heard back from you. Feel free to reach out to me if you want a hand trying to fix this up.

**Pull request closed without merging**
