### PR TITLE
Done

### PR DESCRIPTION
**Pull request by sabtsmith**

### CODE REVIEW

**Comment by mendelB** [comment]
Hey @sabtsmith.
Apologies for the delay in reviewing this pull request!! 😦 

It's looking great, there are just a couple of things that need to be fixed:

You've added your css and custom students index page, you're just missing your custom student card in the `index.html`.
Also, it looks like you've changed the file mode on hundreds of files which might prove problematic to merge. The best way to fix this would be to save your data somewhere, then delete your fork, re-fork and add your work back in and ensure that you're not changing the file modes somehow, then make a new pull request. 
If you need help with any of this you can reach out using the Ask a Question feature on Learn or ping me on Slack @mendel. 
Thanks!

**Comment by sabtsmith** [comment]
Hi Mendel,


I apologize for the delay in responding. I was on holiday and just getting back into my lessons.


To be quite frank, I'm very unclear on the email below. What lesson is that in reference to, what's the exact issue and what are the steps to fix it?  Does this apply to all lessons I've submitted or one in particular? Ive had countless issues with the Learn IDE so I'm not surprised that there's an issue but no clue on what it is and how to address it.


Thanks for your help!
Sabrina


________________________________

**Comment by sabtsmith** [comment]
Hi Mendel,


I wanted to follow up, to make sure I proceed accordingly when completing lessons.


Thanks!
Sabrina


________________________________

**Comment by mendelB** [comment]
Hey Sabrina @sabtsmith 

I'm so sorry! It looks like we keep missing each other on Github :/ 
I'm going to reach out directly on Slack to clarify what needs to be done to fix this.

**Comment by mendelB** [comment]
Hi Sabrina @sabtsmith,
There’s nothing to worry about, the issue is just in reference to this specific lab (the 'deploy day one lab’) and there just seems to be some info missing in the index.html page based on the labs instructions. (You can ignore the other issue about the file modes)
I’d be happy to set up a time to do a quick screenshare and explain what needs to be fixed. please let me know

**Comment by bhollan** [comment]
Hi @sabtsmith !  Have you had a chance to take a look at the needed changes yet?  You need to add your `firstname-lastname.html` profile file into the `students` directory.  You also need to add a reference to that card in `index.html`.

If you need any help at all with any of this, feel free to Ask A Question and we'd be glad to help!

**Comment by bhollan** [comment]
I'm going to close this for now, but if you're still interested in getting your profile into this repo, just let us know and we can help you.  You can re-open this pull request when the time comes, or you can open a new one.

CC: @aturkewi

**Pull request closed without merging**
