### PR TITLE
updated students.learn.co with my profile

### PR DESCRIPTION
**Pull request by terryblue99**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi @terryblue99 !

Your changes look great!  One thing that should be altered though is your CSS changes.  Your rules for `#terry-blue-cover` and `#terry-blue-card` look great, but all those extra lines at the end about `.education-content` are unnecessary.  If you can remove them, I think we can merge your other changes in!

CC: @aturkewi

**Comment by terryblue99** [comment]
Hi,


How do I push my changes from IDE to github?


Thanks.


Terry Blue

**Comment by terryblue99** [comment]
Hi,


I managed to figure out how to push my changes to github so please check and see it's OK now.


Thanks :)


Terry

**Comment by aturkewi** [comment]
Hey @terryblue99 thanks for making some updates!

It looks like you comitted some merge conflict flags though. They look something like `>>>>>>> 79b56d34f7c1ccf728aade9dc834e780d314d6cd` and `<<<<<<< HEAD` and `===========`. You'll have to clean these up before we can merge in this PR. If you're unsure of how to resolve merge conflicts, take a look at this: https://help.github.com/articles/resolving-a-merge-conflict-on-github/ if you still need a hand, please feel free to use Ask A Question :)

**Comment by terryblue99** [comment]
Hi,


I've cleaned up the merge conflicts.


Thanks.


Terry Blue

**Pull request merged**
