### PR TITLE
Done

### PR DESCRIPTION
**Pull request by nicolefederici**

### CODE REVIEW

**Comment by adamjonas** [comment]
hi @nicolefederici. You've only added your student card, we also need the images and styles associated with your profile page.

**Comment by nicolefederici** [comment]
Hey @adamjonas , I just checked and git added every file involved in my entry, including the images and the original student card again. I was told by git that there was nothing to commit and that the working directory was clean. I committed anyway, and was told there was nothing to commit again. I did notice that many students shared the same profile pic. Most notably, a student called Bridger with whom I have chatted on Learn. I know him to be a man. His Learn Students photo is of a beautiful woman. Several profiles share this same photo. I'm wondering if in the merge something is happening wonkily. In that I'm a beginner at Git Hub, I may not understand something I'm doing wrong here. But I believe I have done the correct thing. Please explain how I can fix this. Thank you! Nicole

**Comment by nicolefederici** [comment]
I'm looking at the code on the Learn Git Hub and my images and styles are already there. The only thing missing is my section of index.html which is what I have issued this pull request for.

**Comment by nicolefederici** [comment]
In that this might keep happening, and I think this may have been what happened, I'll throw out a theory: I think students might actually be overwriting other students' cards in the index.html when they enter their info.

**Comment by adamjonas** [comment]
Ok @nicolefederici I'll look into it. Not to worry. I'll sort it out.

**Pull request merged**
