### PR TITLE
Done

### PR DESCRIPTION
**Pull request by tmb41**

### CODE REVIEW

**Comment by mendelB** [comment]
Hey @tmb41,
It seems like you've changed hundreds of files in the repo, which'd prove problematic for us to merge.
You may need to refork and recommit a fixed repo for this to work. (If you need help with this, feel free to post on Ask a Question bar on Learn or ping me on slack @mendel)

**Comment by tmb41** [comment]
@mendelB I made an error here and am going back through some lessons to clean things up. Can you delete/cancel this request?

**Comment by tmb41** [comment]
I see what happened, when I'm forking it doesn't want to pull every other users' files. Is there a more efficient way to do just my files?

**Comment by mendelB** [comment]
@tmb41 The best way to do it is to just pull all the files. (It's a lot but it makes things work smoothly if you do)

**Pull request closed without merging**
