### PR TITLE
Done

### PR DESCRIPTION
**Pull request by Ccordova41**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi Catherine @Ccordova41 !

Looking through your changes here, it seems that you overwrote a fellow student's profile page.
I think it should be pretty easy to fix on your end.  Just type `git checkout students/chris-sexton.html` and then commit/push like normal.

If you can put a note here when that's done, we can probably merge your profile in!

**Comment by Ccordova41** [comment]
Hi There! 

I'm looking over the file and Chris' file appears to be there. 

Thanks!

**Comment by aturkewi** [comment]
Hey @Ccordova41 
Try opening this PR up in github and then clicking on the Files Changed tab above (it'll take you here: https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/632/files)

You can scroll through this page so that you can see all the changes this PR would make if we merged it in. Take a look at Chris' file. You can see at the top it says `students/chris-sexton.html → students/catherine-cordova.html`. This means that you're changing the name of it and just filling in your information instead. Take a look at your fork of this repo and the files there: https://github.com/Ccordova41/learn-deploy-on-day-one-v-000/tree/master/students. You'll see Chris' file is in fact not there anymore. You can still find his file on this repo though because we have not merged in your PR.

What you need to now do is bring Chris' file back with `git checkout 0495ea1 students/chris-sexton.html` This will bring this file back from the previous commit. When you do this, it may remove your file, so you might have to re-create it. The easiest way to work off of a previous students page without over-writing it is to `cp students/chris-sexton.html students/catherine-cordova.html`. This will make a copy of the file, rather than over-write it. 

Once you take a look at all of this, please let us know if you still need a hand!

**Comment by ivalentine** [comment]
Hi @Ccordova41! I'm going to close this pull request. If you would like to make the above changes and have us merge them in, just re-open this pull request and let us know.

Thanks!

cc @aturkewi

**Pull request closed without merging**
