### PR TITLE
Brian cooper profile

### PR DESCRIPTION
**Pull request by bjacooper**
Added my profile. Cheers, Brian

### CODE REVIEW

**Comment by mendelB** [comment]
Hey @bjacooper. Things are looking good. two issues though:
It looks like you've changed someones profile page and edited it with your data, you need to create your own, otherwise we'd be erasing someone elses profile :)
Also, you're missing the customized div in the `index.html` page with your info.
If you need any help with this stuff - jump on Ask a Question, or ping me on slack @mendel 
Thanks!

**Comment by bjacooper** [comment]
Oooops!

Sorry about that, I'll do this again tomorrow :)

**Comment by mendelB** [comment]
Hi there. Don’t worry about the closed pull request. We’ve had to do some major construction to this lab, but in the next few days we will merge your code manually to the repo and your profile will appear on the site. Thanks for your patience and happy coding!!

**Comment by bjacooper** [comment]
Oh, I actually forgot about this... I think I still have some changes to
make, no? Didn't I delete something else's profile?

**Comment by mendelB** [comment]
All we're missing from you is your profile card for the `index.html` page. If you can get that done and just push that to your repo and let me know here that'd be awesome!

**Pull request closed without merging**
