### PR TITLE
Done

### PR DESCRIPTION
**Pull request by Idayat8703**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi @Idayat8703 !

Looking over your changes here, it looks like you forgot to edit `css/styles.css`.
Also, your card in `index.html` seems to have all the right pieces, but is not properly indented.  All closing tags should be indented to the same level as the matching opening tag and everything in between should be at least indented further than the opening line.  Like this:
```
<div>
   <p>Some paragraph or other.</p>
   <div>
      <p>Another paragraph</p>
   </div>
</div>
```

Make your `index.html` indented properly and modify `css/styles.css` and we can see about merging these changes in.

As always, feel free to Ask A Question if you need any help getting things squared away.
CC: @aturkewi

**Comment by aturkewi** [comment]
These indents still don't seem to line up. When I look at your changes here, I see your code looks like this:
```html
          <div class="student-card" id="idayat-oshobajo-card">
              <a href="students/Idayat-Oshobajo.html">
              <div class="view-profile-div">
              <h3 class="view-profile-text">View Profile</h3>
                </div>
                <div class="card-text-container">
                <h4 class="student-name">Idayat Oshobajok</h4>
                <p class="student-location">Brooklyn, NY</p>
              </div>
                </a>
              </div>
```

Compared to the one above:
```html
<div class="student-card" id="michael-burak-card">
    <a href="students/michael-burak.html">
        <div class="view-profile-div">
            <h3 class="view-profile-text">View Profile</h3>
        </div>
        <div class="card-text-container">
            <h4 class="student-name">Michael Burak</h4>
            <p class="student-location">Bayonne, NJ</p>
        </div>
    </a>
</div>
```

If you look, you can find the end of each `div` tag by looking straight down in a line. Does that make sense? Let us know if you need a hand properly indenting your code in a similar format :)

**Comment by Idayat8703** [comment]
I  will look into this later this evening

**Comment by Idayat8703** [comment]
I updated the changes for indenting my html page. Hopefully it's good now.

**Comment by aturkewi** [comment]
Hey @Idayat8703 thanks for making an update :)

I think I should have been more clear in my previous comment. The file that I was talking about regarding the indentation file is the `index.html` file.  If you look at my comment from 3 days ago, that's where that HTML is from. You can see all the changes to be merged here in the Files tab (https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/716/files)

If you take a look, you can see that all the changes you just made were to your specific page and it looks like you still need to make changes to the `index.html`

If you'd like a hand with this and have some one go over it with you live, you can use the Ask A Question button in Learn to have a Learn Expert lend a hand :)

**Comment by Idayat8703** [comment]
Okay. I fixed it now. Hopefully this works. Sorry about the confusion.

Thanks,
Idayat

**Comment by aturkewi** [comment]
Hello! We recently made a change to this repo that caused all open PRs to be close and we are not able to re-open them. I'm very sorry about the inconvenience, but I just wanted to let you know why this PR was close and that we still welcome your profile on the site! So if you're still interested in having your profile up, please feel free to open another PR.

**Pull request closed without merging**
