### PR TITLE
Added my information and fixed a couple of errors

### PR DESCRIPTION
**Pull request by thebrianemory**
There was an extra `</div>` after Kailee Gray's information. Also removed the `<center>` as suggested by the W3C validator. Ran the validator on the CSS and `#michael-casciato-cover` ended with `''` instead of `;`.

### CODE REVIEW

**Comment by aturkewi** [comment]
Hey @thebrianemory 

Thanks for pointing out some issues! I already got rid of the extra div, and we're going to leave that center tag in for now. I hadn't caught that `''` though, so good catch :+1: 

It looks like you're missing your profile page and both your photos though. If you add those into this PR and put that center tag back in, I'll be able to merge this PR. 

Feel free to message me if you need a hand with any of this.

**Comment by thebrianemory** [comment]
Hi @aturkewi 

As soon as I read your reply I knew what I had done. I noticed on a later lesson the git command for staging files I was using did not add newly created files. At the time I was wondering what other lessons I missed that on.

**Comment by aturkewi** [comment]
@thebrianemory Looks great! I'm gonna merge this!

Also, about the center tag: We have very specific changes that we're looking for students to make on this page. As I'm not the designer of the page, I generally don't allow any overall design changes from students to merge in. BUT after talking with some one about the center tag, I found that that it was actually recently added by a student and as you pointed out, it doesn't really look like it's supposed to be there. So I just wanted to follow up with you on this to give you the full story and let you know that I will be removing it shortly. Thanks again for pointing it out and I'm sorry I had asked you to removed it from this PR! :+1:

**Comment by thebrianemory** [comment]
@aturkewi 

Ah I see. I only noticed because I ran it through the validator. With the large size of the documents I was worried about accidentally typing something where it didn't belong. Or my personal favorite, leaving out some important punctuation. :relaxed:

Glad it all worked out and I could be of some assistance!

**Pull request merged**
