### PR TITLE
nick-ratti info added

### PR DESCRIPTION
**Pull request by ratdog19336**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi @ratdog19336 !

Looking over your changes here, your CSS and Profile look ok.  I don't see a reference to your profile built into `index.html`.  If you can add that in, we can probably get your profile merged in.

CC: @aturkewi

**Comment by ivalentine** [comment]
Hi @ratdog19336! When you get a chance, could you add a reference to your profile in `index.html`? Once you've made those changes, we'll be happy to take another look at this pull request.

Thanks!

cc @aturkewi

**Comment by ratdog19336** [comment]
Did I not?  I believe I pushed these to git-hub?

**Comment by bhollan** [comment]
@ratdog19336 Not that we can see.  If you click on the "Files Changed" tab you can see the files that have been changed for this pull request, as well as highlights of what's been changed.

If you've committed them to your local repo, you should be able to see the commit when you run `git log`.  Compare that to the list of commits that are attached to this pull request and see if you need to push or code or commit or all of the above.

And as always, feel free to Ask A Question about this.  I had to fix another student's IDE connection to get theirs to work last week.  But if you can't see it on github, we can't see it either.  :)

**Comment by bhollan** [comment]
Hi @ratdog19336 !

So I see that you've pushed some new changes, but we still can't see any changes to `index.html`.  It's possible that you're not `commit`ing or `push`ing what you think you are.  You can Ask A Question about this lab if you'd like some help figuring it out.

CC: @aturkewi

**Comment by ratdog19336** [comment]
I did and PJ told me that he could see the changes I made a month ago as well as the resubmission I did yesterday.  I’m really not sure what is going on where we can’t get this solved.  I guess I can try to do the same thing tomorrow.

Thanks!
-Nick

**Comment by aturkewi** [comment]
Hey @ratdog19336 Some things to take a look at here. If you look at the top of this page https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/640 you can see that you are making a pull request from your fork of this repo's master branch. You _also_ have a branch named after you it looks like. Because you are making this PR from your fork of the master, that's where the changes need to be. 
You can also look at this link: https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/640/files to see what changes are actually going to be made when we merge this PR in. That's the key thing we look at. If you still need help with this, try using the AAQ button again and make sure to link them to this PR so they can see everything that's going on :)

Sorry for all the confusion here, but I think you've almost got this!

**Comment by ratdog19336** [comment]
So hopefully this is working now.

**Comment by bhollan** [comment]
Hi @ratdog19336 !

This is looking great!  All I see is one extra closing `div` tag.  I've made a comment on the line and if you can remove the extra tag, I think we can merge your profile in.

CC: @aturkewi

**Comment by ratdog19336** [comment]
Sounds good Brian - I'll get that done tonight.

-Nick

**Pull request merged**
