### PR TITLE
Done

### PR DESCRIPTION
**Pull request by michellejanosi**

### CODE REVIEW

**Comment by mendelB** [comment]
Hey @michellejanosi, it looks like there are thousands of lines changed in the css/styles.css file. Please make sure you're just adding your own styling and not changing the whole file. Let me know when you update the branch so I can merge it. Thanks!

**Comment by michellejanosi** [comment]
I apologize for the error @mendelB Forgot to push changes to profile branch prior to pushing to master. I redid that so hopefully all is good. Thanks! Let me know.

**Comment by mendelB** [comment]
No problem @michellejanosi.
Though I think to fix the issue you may need to delete your fork, refork and redo the lab so that all the deletions and additions to css/styles don't mess up the repo.
Thanks!

**Comment by aturkewi** [comment]
New PR to replace this one #301

**Pull request closed without merging**
