### PR TITLE
Done

### PR DESCRIPTION
**Pull request by BriOD**

### CODE REVIEW

**Comment by ivalentine** [comment]
@BriOD Hi Brian! I've reviewed your pull request, and it looks like you've overwritten another student's page with your own. Please restore that page and create a separate page for yourself. Once you've made those changes, go ahead and update this pull request and we'll be happy to take another look.

If you have any questions, feel free to Ask a Question on this lesson on Learn. Thanks!

cc @aturkewi

**Comment by bhollan** [comment]
Hi @BriOD!

I think we're going to close this for now.  It's still here and ready to go in whenever you're ready to get the requested changes in.  Feel free to Ask A Question for help and/or re-open this PR whenever you're ready.

CC: @aturkewi

**Comment by BriOD** [comment]
Oh, I apologize. I saw this, and then forgot about it. What do I have to do to resolve this issue?

**Comment by bhollan** [comment]
It looks like you overwrote `aaron-enser.html`'s file.  So in your branch, you should be able to do `git checkout master:students/aaron-enser.html`.  Either that or just manually make sure that his profile AND your profile are both in the `students` folder.

CC: @aturkewi

**Comment by BriOD** [comment]
ok i think i fixed it. i opened up my cloned copy, manually added aarons html page, and ran learn submit again. i hope this fixed it. if it didn’t and you need me to do something else please let me know. sorry for the inconvenience.

**Pull request merged**
