### PR TITLE
Done

### PR DESCRIPTION
**Pull request by echi81**

### CODE REVIEW

**Comment by mendelB** [comment]
Hey @echi81 
Apologies for the delay in reviewing this pull request!! 😦

It's looking great, there are just a couple of things that need to be fixed:

You need to add your student card to the `index.html` file, and your css to the `styles.css` file.
It also seems like you've overwritten someones student index page with your own data.
Mainly: it looks like you've changed the file mode on hundreds of files which might prove problematic to merge. The best way to fix this would be to save data somewhere else temporarily, then delete your fork, re-fork and add your work back in including the changes and fixes, and ensure that you're not changing the file modes somehow or overwriting someone else's work, then make a new pull request. 

If you need help with any of this you can reach out using the Ask a Question feature on Learn or ping me on Slack @mendel. 
Thanks!

**Comment by aturkewi** [comment]
@mendelB are the file modes still an issue? Or does @echi81 only need to fix the `index.html` and the `style.css` as mentioned above?

**Comment by mendelB** [comment]
Hey @aturkewi Good point! 
@echi81 The file modes are no longer an issue, so it'd just be a matter of fixing the other two issues.

Thanks for pointing that out!

**Comment by aturkewi** [comment]
Hey @echi81 I'm going to close this PR. If you'd still like your profile merged in, please re-open this PR and let us know and we'll be happy to help.

**Pull request closed without merging**
