### PR TITLE
Done

### PR DESCRIPTION
**Pull request by mmelmer**

### CODE REVIEW

**Comment by mendelB** [comment]
Hey @mmelmer 
It looks like you've changed thousands of files in this repo which would make it problematic for us to merge, please recommit your files without all the changes.
(If you need help with this, use the 'Ask a Question' button on the top right if the lab, or ping me on slack @mendel) 
Thanks!

**Comment by mmelmer** [comment]
Mendel,

when I forked the lab last night and copied the files, a great number of
the required files were not present. I tried again, with the same result. I
asked for help via the online chat and was directed to copy the necessary
files from the lab's github page - so I just copied those into the
forked/copied folder in order to get everything to work. Should I try to
re-open/fork the lab?  thanks!

**Comment by mendelB** [comment]
Yea I'd say to try to copy your new code somewhere and  delete your repo and try to refork and redo the lab

**Comment by aturkewi** [comment]
@mmelmer I'm closing this PR as it's been inactive for over two weeks. If you would like some help to get this working, please message myself or Mendel on Slack and we'll help you out (on slack i'm avidor, and mendel is mendel).

**Pull request closed without merging**
