### PR TITLE
Done

### PR DESCRIPTION
**Pull request by Jschles1**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi!  It looks like you've added images to a folder, which we are trying to avoid in this repository.  Also, you haven't made any changes to any of the necessary files.

I suggest you review [the lesson](https://learn.co/tracks/full-stack-web-development/html-and-css/css/deploy-your-profile-page) and try again.

**Comment by Jschles1** [comment]
Hey Brian,

I looked over the lesson and my code several times and I'm pretty sure I
followed the directions as given. Maybe there is something wrong on your
end where you can't see the changes? Please correct me if I did something
wrong.

I made the specified changes to the style.css, adding my profile and cover
photos at lines 136 and 140.

I created and added my own student.html file (john-schlesinger.html), with
the required information, and added it to the students directory.

I added my own div with the required information to index.html at line 38.

You said that I wasn't supposed to add the images to the folder, but it
says under "Add Your Profile Page" in the directions, that I should add my
profile picture and cover photo to the img directory?

I added pictures to show exactly where I made the specified changes.

Thanks,

John Schlesinger

**Comment by bhollan** [comment]
Is it possible that the changes never got commited/pushed?  Look through the PR on github so you can see what I see.  Once your changes are up on github we can probably merge them in.
The "Commits" tab will show you if/when you commited that's been pushed to github.  If you run `git log` you should basically see exactly what's there.

Again, feel free to use Ask A Question to figure everything out if you want to do it that way.

**Comment by bhollan** [comment]
Hi I see you deleted the two pictures.  Nice work!  I also see your screenshots and they look great!  I'd love to merge them in!  However, I'm still not seeing your changes in the repo on github.  Are you sure you've commited and pushed them?

If you can see your changes at this link, then something very strange is going on.
https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/549/files

I think it would be good if you could Ask A Question from on this lesson when you have a chance.  I'm on duty some this week, but whoever you get should be able to figure out what's going on.

CC: @aturkewi

**Comment by Jschles1** [comment]
Hey Brian, I'm not seeing any of the changes on the link you provided. I'll
definitely get assistance from someone on Learn when I get the chance.

Thanks,

John Schlesinger

**Comment by bhollan** [comment]
I'll be on duty tomorrow afternoon and night if you'd like to try to get together on this @Jschles1

**Comment by Jschles1** [comment]
Sorry I just saw your message. I'll post this thread to the ask a question in about 30 minutes.

**Pull request merged**
