### PR TITLE
add Jenna Mandel profile to index 

### PR DESCRIPTION
**Pull request by jblair87**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi @jblair87 !

Looking over your changes here, it looks like you have a commit titled "Delete CNAME".  Can you restore that file by running `git checkout CNAME`?  You'll have to `commit` and `push` again after that.  Then I think we can merge your changes in.

As always, feel free to Ask A Question if you need any help getting things squared away.
CC: @aturkewi

**Comment by bhollan** [comment]
You have another PR against this repo.  I'm going to close this one.

CC: @aturkewi

**Comment by jblair87** [comment]
ah Sorry @bhollan ! This was confusing because I thought my code was broken as it wasn't showing up on the site so I deleted my local branch, forked the repository again and did a new pull request. 

This was before I learned about the code needing to being merged after someone reviews it. I am learning about open source. 

I had contacted someone about the CNAME file as well.  I can restore it now if you need me to.

**Comment by bhollan** [comment]
You're doing great!  Keep it up!

Don't worry about `CNAME` for now.  Since you had 2 and the other one was in much better shape, I closed this one.

But you can fix one indentation in your `index.html` file (I made a note in the other PR).

Let me know if you need any help!

**Pull request closed without merging**
