### PR TITLE
Done

### PR DESCRIPTION
**Pull request by ICanDoAllThingThroughChrist**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi @ICanDoAllThingThroughChrist Charlie!

It looks like you've created a nice profile page.  It also looks like you've forgotten to edit `index.html` and `css/styles.css`.  Take a look at the lesson and see if those needed changes make sense.

Feel free to Ask A Question about this lesson if you need any help.

CC: @aturkewi

**Comment by bhollan** [comment]
Hi @ICanDoAllThingThroughChrist Charlie!

So this is looking MUCH better!  Two last things though.  One: It looks like you changed the `.details-block` CSS rule from `33` to `100`.  I'm sure you did it for good reason, but this will affect all other students and should remain unchanged.  Two: In `index.html` it looks like you renamed a fellow student's card to become your own instead of copy/paste/edit-ing a new one for yourself.  So if you can re-instate his card and create one for yourself, then I think we can get this merged in.

As always, feel free to Ask A Question if you need any help getting things squared away.
CC: @aturkewi

**Comment by bhollan** [comment]
Hi @ICanDoAllThingThroughChrist Charlie!

I'm going to close this PR for now.  We can re-open it any time you like.  Just let us know whenever you're ready to implement the necessary changes.

If you need any help, as always, please feel free to Ask A Question!

CC: @aturkewi

**Comment by ICanDoAllThingThroughChrist** [comment]
I thought i completed this request. it does not seem the result was
accepted, is that correct?

**Comment by bhollan** [comment]
If you click on the "Files Changed" tab, you can see what we see.

https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/667/files

On that tab, you'll see the changes that I referenced in the comments/messages.  So if you've fixed those changes locally, you still have to `commit` and `push` them before they'll show up here.

**Pull request merged**
