### PR TITLE
Done

### PR DESCRIPTION
**Pull request by marineb**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi Marine! @marineb 

Looking over your changes, everything I see looks good.  What I *don't* see is a reference to your profile in `index.html`.  If you can add that in, I think we can merge these changes in.

**Comment by marineb** [comment]
Hi @bhollan. Sorry about that! I updated the homepage. Now my branch has conflicts. Do I need to rebase or something? Thank you!

**Comment by bhollan** [comment]
@marineb 

I don't see the merge conflicts you're talking about, but in looking at it, it does seem like there's an extra closing `</div>` tag in `index.html` that looks like it should be deleted.  Can you take care of that?  I think that's the last thing holding up merging this in.

**Comment by marineb** [comment]
Hi @bhollan should be good to go now. I actually saw 2 extra divs. Which I removed. Thank you!

**Comment by ivalentine** [comment]
Hi @marineb! I took a look at your last commit, and it looks like it introduced many changes into `index.html`, which are causing many merge conflicts. I would recommend reverting that commit with `git revert 96f6b3a` and re-adding the reference to your profile on that page.

Once you've made those changes, just let us know and we'll be happy to take another look. Thanks!

cc @aturkewi

**Comment by marineb** [comment]
Hi, sorry about that (again). Should be good to go now?

**Pull request merged**
