### PR TITLE
Done

### PR DESCRIPTION
**Pull request by whalien52**

### CODE REVIEW

**Comment by mendelB** [comment]
Hey @whalien52, it looks like you deleted and/or re-added many files. Please fix those changes (perhaps re-fork the repo and start again) and let me know when you've committed your changes so I can merge. Thanks!

**Comment by whalien52** [comment]
Hello!
Yeah I ended up having to download the zip file from github. Each time I
tried to use the Learn open command it would either fail or only clone the
readme file. I got to it 'successfully clone' this morning but I was
missing over half of the repository.

**Comment by mendelB** [comment]
@whalien52 Perhaps try to delete your fork, and then manually fork the repo on github, and clone it locally. that way you should be guaranteed to get the full repository. (If you need help with that, be sure to ask on the lab on Learn.co)

**Comment by aturkewi** [comment]
Hey @whalien52, are you still having issues forking and cloning this lab? If you need a hand, I'm on slack as avidor, and I'd be happy to help!

**Comment by aturkewi** [comment]
@whalien52 I'm closing this PR. Feel free to open it back up if you make the changes. Feel free to contact Mendel or myself if you'd like hand with this.

**Pull request closed without merging**
