### PR TITLE
Adding Eva Navarro to the public student directory

### PR DESCRIPTION
**Pull request by Emanao**

### CODE REVIEW

**Comment by bhollan** [comment]
Hi @Emanao !

Looking at your changes, it looks like you've made many small changes to the layout of the file.  Most of your changes that were intended from the lesson seem ok, but we try to keep changes to this repo very, very small.  So if you could go back and change your files to be very small changes, I think we can eventually merge this in.

Let us know if you need any help!

CC: @aturkewi

**Comment by aturkewi** [comment]
@Emanao specifically it looks like you somehow changed the spacing structure of the entire file (changing the indent from 2 spaces `  ` to 4 spaces `    `. These are some massive changes that we cannot merge in. I think your best option might be to save the changes you want to make (your student page, your card on `index.html` and your css) to a separate file. You can then either rollback your changes on this repo, or just delete it and restart. 

Then when you make your desired changes, make sure _not_ to run any auto formatting in your editor that might change spacing across many files.

Give this a try and if you still need a hand, feel free to use Ask A Question to get some help :)

**Comment by Emanao** [comment]
Hi!
I was using visual code with the beautify extension and I think that this is the result of it :(
Do you want me to redo it?
Eva

**Comment by aturkewi** [comment]
If you can undo that change, that would be perfect. If not, then yes, you'll have to redo it.
We are really only looking for the changes specified. It's not that 2 spaces is necessarily better or worse than 4 spaces, but this repo would become chaotic if every student made large changes so the repo was to their preference :)

Some good tips to learn from this though are to check what changes you're comiting with `git status` (to see the files changed) and then `git diff` (to see the actual changes per file). This will let you keep an eye on what edits you are attaching to each commit message. Also, when you put in the PR, you can look at the Files Changed tab on GitHub and review to make sure those are the changes you intend to make on a project :)

This may seem like a pain, but it's great experience to have for working collaboratively on projects.

**Comment by Emanao** [comment]
Hi again,
I have my files ready to be pushed in Github, but I have a question: should I just push them in GitHub leaving the bad ones with extra spacing there or should I erase my last version in Github and then push them? If it is the last case I would need some help since I have no clue how to do that :)
Thanks.
Eva

**Comment by Emanao** [comment]
Hi again
I just submitted the files through the Learn IDE. Please let me know if everything is ok now. 
Thanks
Eva

**Comment by bhollan** [comment]
Hi @Emanao !  This is looking so much better!  Thanks for looking into this.  It looks like the rest of the file is back to the way it should be, so we should be able to merge this in after 1 more minor change.  It looks like you forgot to change the spacing of *your card* inside `index.html` from 4 spaces to 2.  If you can just make those changes and push them up to github, we should be able to merge this in.  Thanks!

CC: @aturkewi

**Comment by bhollan** [comment]
It looks like you haven't touched this in a while.  I'm going go to close it for now and we can open it again whenever you're ready to work on it.  We can get it merged in then.

CC: @aturkewi

**Pull request closed without merging**
