### PR TITLE
Lkw la la master

### PR DESCRIPTION
**Pull request by adamjonas**

### CODE REVIEW

**Comment by adamjonas** [comment]
@LKWLaLa this has been merged, but it would be great to push a picture without a mask. It looks a little weird with a circular picture on the index page.

**Comment by LKWLaLa** [comment]
Hi Adam,

Sure thing.  Would you prefer I change my photo and submit the pull request again, or just email a replacement?

**Comment by adamjonas** [comment]
New PR!

**Comment by LKWLaLa** [comment]
ok! :)  New PR coming up!

**Pull request merged**
